version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mydb-dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=db
      - DB_NAME=mydb-dev
      - DB_USER=dev
      - DB_PASS=password
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: npm start
